version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-compose
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
      - node-modules:/fontend/node_modules

volumes:
  node-modules: