import type { NextPage } from 'next'
import Head from 'next/head'
import { Button } from '@mui/material'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main>
        <p>Hello World!</p>
        <Button variant="contained">MUI Button</Button>
      </main>
    </div>
  )
}

export default Home
