import type { NextPage } from 'next'
import Head from 'next/head'
import { Button } from '@mui/material'

/*const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Hello World!</p>
        <Button variant="contained">MUI Button</Button>
      </main>
    </div>
  )
}

export default Home */

const Home: NextPage = () => {
  return (
      <div>
          <Head>
              <title>New DOmain Page</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
              <link rel="stylesheet" href="global.css"/>
          </Head>

          <main>
              <h1>Create New Domain</h1>

              <div>
                  <label>
                      Domain Name:
                      <input type="text" name="name"/>
                  </label>
              </div>
  
              <div>
              <label id="desc_label">
                  Description: 
                  <textarea id="descbox-style" placeholder="enter description"/>
              </label>
              </div>
              
              <Button id="btn_padding" variant="contained">submit</Button>
          </main>
      </div>
  )
}
export default Home