import type { NextPage } from 'next'
import Head from 'next/head'
import { Button } from '@mui/material'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Hello World!</p>
        <Button variant="contained">MUI Button</Button>
      </main>
    </div>
  )
}

export default Home
